
-- LIST OF DEFAULT SCHEMAS IN POSTGRES
-- INCLUDES INFORMATION_SCHEMA, PG_CATALOG, PG_TOAST AND SO ON ....


-- COMMAND TO LIST ALL THE SCHEMAS IN POSTGRES
SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA;

-- ALTERNATIVE COMMAND TO LIST ALL THE SCHEMAS IN POSTGRES
SELECT NSPNAME FROM PG_CATALOG.PG_NAMESPACE;

-- COMMAND TO LIST ALL THE SCHEMAS IN A GIVEN DATABASE

-- ****** LIST TABLES IN ALL SCHEMAS ******** --- 
\DT *.* ;                -- LIST ALL TABLES IN ALL SCHEMAS.

-- ****** LIST TABLES IN A PARTICULAR SCHEMA ********* --
-- SAY INFORMATION SCHEMA
\DT INFORMATION_SCHEMA.* ; -- LIST ALL TABLES IN INFORMATION_SCHEMA.*

